CREATE DATABASE Vendas_FranciscodasChagas

ALTER DATABASE [Vendas_FranciscodasChagas] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET ARITHABORT OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Vendas_FranciscodasChagas] SET CURSOR_DEFAULT  GLOBAL